### ISSUE TITLE
ImportError: cannot import name 'smart_text'

### ISSUE THREAD

**Issue by sklirg** [GetBlimp/django-rest-framework-jwt#141]
I'm getting

```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/settings.py", line 172, in import_from_string
    module = importlib.import_module(module_path)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework_jwt/authentication.py", line 4, in <module>
    from rest_framework.compat import smart_text
ImportError: cannot import name 'smart_text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/vagrant/venv/urls.py", line 8, in <module>
    from venv.apps.api.utils import SharedAPIRootRouter
  File "/vagrant/venv/apps/api/utils.py", line 2, in <module>
    from rest_framework.routers import DefaultRouter, SimpleRouter
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/routers.py", line 25, in <module>
    from rest_framework import views
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/views.py", line 96, in <module>
    class APIView(View):
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/views.py", line 101, in APIView
    authentication_classes = api_settings.DEFAULT_AUTHENTICATION_CLASSES
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/settings.py", line 208, in __getattr__
    val = perform_import(val, attr)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/settings.py", line 160, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/settings.py", line 160, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/home/vagrant/.virtualenvs/venv/lib/python3.4/site-packages/rest_framework/settings.py", line 176, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework_jwt.authentication.JSONWebTokenAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: cannot import name 'smart_text'.
```

using the fix in #140 (which resolves #139 )

Looks like https://github.com/tomchristie/django-rest-framework/commit/d54c67d79d0f5661ef33d860efe80a4272e22b3e removed smart_text from rest_framework.compat. (This was back in dec 2014, though?)

I'm using Django 1.8.3, with rest_framework 3.2.0 and the fix proposed in #140.

Anyone else experiencing this?

_EDIT:_ Forgot to change title before posting... my bad.

**Comment by cgroner** [comment]
It looks like you're using an old version of `django-rest-framework-jwt`. 

The line generation the `smart_text` error [was changed here](https://github.com/GetBlimp/django-rest-framework-jwt/commit/d4ff802289b6206cb1feb06d3aa0f41b74e2c2e0#diff-642f49966b24de36b34353754525c56c).

**Comment by sklirg** [comment]
Okay that's weird, must've come from the pull request using an old version? I might have time to look at forking the fix and pulling upstream over the weekend.

Thanks for the reply!

**Comment by sklirg** [comment]
This was indeed the pull running an old version. Installed this package using latest commit last night, and it worked. Closing this.

**Comment by AHLinJie** [comment]
from django.utils.encoding import smart_text
