### ISSUE TITLE
1.7 python manage.py cry

### ISSUE THREAD

**Issue by frlinw** [GetBlimp/django-rest-framework-jwt#148]
Hi,

it's 4:45am here, good time for a lil pip update  (and some tears) !

manage.py doesn't love me anymore

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenvs/diagenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenvs/diagenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/opt/virtualenvs/diagenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/virtualenvs/diagenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/virtualenvs/diagenv/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/projects/diagenv/diagproject/app/models.py", line 13, in <module>
    from app import helpers
  File "/opt/projects/diagenv/diagproject/app/helpers.py", line 6, in <module>
    from rest_framework_jwt import utils
  File "/opt/virtualenvs/diagenv/lib/python2.7/site-packages/rest_framework_jwt/utils.py", line 6, in <module>
    from rest_framework_jwt.compat import get_username, get_username_field
  File "/opt/virtualenvs/diagenv/lib/python2.7/site-packages/rest_framework_jwt/compat.py", line 12, in <module>
    class Serializer(rest_framework.serializers.Serializer):
AttributeError: 'module' object has no attribute 'serializers'
```

Any idea ?

**Comment by jpadilla** [comment]
Related to #151
