### ISSUE TITLE
`django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.` when importing JSONWebTokenSerializer

### ISSUE THREAD

**Issue by Symmetric** [GetBlimp/django-rest-framework-jwt#177]
I'm trying to subclass JSONWebTokenSerializer (to override the `username_field`), and if I simply import `from rest_framework_jwt.serializers import JSONWebTokenSerializer` at the top of my `models.py` file, I get the following error:

```
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/paul/.virtualenvs/app/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/paul/git/app/monolith/user/models.py", line 5, in <module>
    from rest_framework_jwt.serializers import JSONWebTokenSerializer
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/rest_framework_jwt/serializers.py", line 17, in <module>
    User = get_user_model()
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/rest_framework_jwt/compat.py", line 32, in get_user_model
    User = get_user_model()
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/paul/.virtualenvs/app/lib/python3.4/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

Digging around a bit, there's a stackoverflow [answer](http://stackoverflow.com/a/25648427/37481) that suggests the `get_user_model()` usage in `rest_framework_jwt/serializers.py` might not be correct, but that is a shot in the dark.

**Comment by vaibhav-jain** [comment]
@Symmetric I did similar thing because I wanted to override `username` field But in `Serializers.py` and it works like a charm. Thing about `get_user_model` is it can only work after all the apps and their models are loaded. But as In your case you are breaking the pattern by calling `get_user_model` by importing `JSONWebTokenSerializer` .  And about `settings.AUTH_USER_MODEL` Use it in places like models.py which needs lazy loading of models otherwise its wise to use `get_use_model()` other places like in `forms`, `views` , `serializers`

**Comment by carltongibson** [comment]
> I'm trying to subclass JSONWebTokenSerializer (to override the username_field), and if I simply import from rest_framework_jwt.serializers import JSONWebTokenSerializer at the top of my models.py...

Yeah. Don't do this. Create a separate serialisers file, and import that to your views. This gives Django time to complete the `setup()` phase.
